from .birdTag import birdTag
from .dvl import DVL
from .main_func import readAxy,
    readDVL,
    readBIP,
    gps_distanceSingle,
    dtFormat,
    gps_speed,
    distSpeed,
    main_func,
    removeNearCS,
    lowEquiFilt,
    accFeatures,
    hammingSpect,
    rollingSpecSum,
    reduceErroneous,
    maxWithGap,
    flightestimate,
    find_gaps,
    peak_trough,
    interpeaktrough,
    flap,
    flight_pitch_changes,
